### PR TITLE
iconvert.rb: fix homepage

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by reitermarkus** [comment]
@vitorgalvao, thanks! How the hell did you end up *here*? 😂

**Comment by vitorgalvao** [comment]
1. From https://github.com/caskroom/homebrew-cask/issues/29995#issuecomment-278877724 I thought “I wonder if he has the script in his repos”.
2. So https://github.com/reitermarkus?tab=repositories and “let’s see if there’s anything else interesting, while I’m here”.
3. I found https://github.com/reitermarkus/epub-services, saw the README and though “why isn’t this in the main repo? I wonder if it has something to do with anything else in that tap”.
4. https://github.com/reitermarkus/homebrew-tap and “ah, there are casks *and* formulae here, but why aren’t these casks in the main repo?”.
5. https://github.com/reitermarkus/homebrew-tap/tree/master/Casks and “iconvert? I wonder if it’s [that iconvert](https://iconverticons.com/). If it is, I can recommend [an alternative method](https://github.com/vitorgalvao/tiny-scripts/blob/2ba74c9bb1acc66585dd23d3f06d2a4a45b4dd54/customise-terminal-notifier#L45-L59)”.
6. So finally I opened http://www.rmartijnr.eu/iConvert/index.html, it 404’d, found the new homepage and submitted.

**Comment by reitermarkus** [comment]
I just love your level of detail.

And as to “why this isn't in the main repo”, most of these are unofficial/legacy, and `epub-services` is “not popular enough“.

**Comment by vitorgalvao** [comment]
> and `epub-services` is “not popular enough“.

Though that is [technically correct](http://youtu.be/hou0lU8WMgo), I also feel it obeys the [letter of the rule, and not its spirit](https://en.wikipedia.org/wiki/Letter_and_spirit_of_the_law).

To me the rule is important so a random user doesn’t just add every personal script they make and abandon a month later, cluttering the repo with forgotten casks. While [maintainers may also forget about their casks](https://github.com/caskroom/homebrew-cask/pull/29364), you’re an active maintainer so it’s unlikely you’d forget the cask is there or fail to update it.

I’d have no problem having it in the main repo.

---

Unrelated, your logo on twitter is slightly different than the one on github and your website (it’s shifted). Is that on purpose?

image
image

**Comment by reitermarkus** [comment]
> I’d have no problem having it in the main repo.

I'm not sure the services even work anymore, but I'll submit it to the main repo when I get around to testing/updating them.

> Is that on purpose?

No, I forgot to update it on Twitter, it seems.

**Pull request merged**
